### Booking HTTP tests for BookingServiceImpl via BookingController

@bookingId = 7

###Create booking
POST http://localhost:8080/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiR1VFU1QiLCJ1c2VySWQiOiIxIiwiZW1haWwiOiJyb2pvQGdtYWlsLmNvbSIsInN1YiI6InJvam9AZ21haWwuY29tIiwiaWF0IjoxNzYwMjAxMjU4LCJleHAiOjE3NjAyMDQ4NTh9.5LVp_U3tSXdw_cg5aGNK0_-oPNdDFtI1zQcN87goflaFOZWesMNZiiexwDs0eIIvpexxN0X4rZCtm929EoJ08g

{
  "idAccommodation": 6,
  "dateCheckIn": "2025-10-18",
  "dateCheckOut": "2025-10-20",
  "guestsCount": 4,
  "notes": "Sin comentarios"
}

###Search filtered booking
GET http://localhost:8080/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiR1VFU1QiLCJ1c2VySWQiOiIxIiwiZW1haWwiOiJyb2pvQGdtYWlsLmNvbSIsInN1YiI6InJvam9AZ21haWwuY29tIiwiaWF0IjoxNzYwMTU2NTk0LCJleHAiOjE3NjAxNjAxOTR9.t-4xzmyB1Vi4AZ2vZ6cgayjJ1o7iABvMnvazn_hgJg4lrWB03xljuBlRhYZj5mc7uesAOHIqffJZIzaWiTePmg

{
  "price": 1500000
}

###Get bookings' detail
GET http://localhost:8080/bookings/{{bookingId}}/detail
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiSE9TVCIsInVzZXJJZCI6IjQiLCJlbWFpbCI6InZlcmdhcmF3aWxsaW50b24wNEBnbWFpbC5jb20iLCJzdWIiOiJ2ZXJnYXJhd2lsbGludG9uMDRAZ21haWwuY29tIiwiaWF0IjoxNzYwMTU1NjI0LCJleHAiOjE3NjAxNTkyMjR9.VxwCJ4bXsTLWGOkSPgeYH4F0TF18O6JcBK9m6wJqSknHh_32gog-Qb6ykUV-VuLvrDW1Ep9Zz_UW4hA-dl7l3g

###Confirm booking
PUT http://localhost:8080/bookings/{{bookingId}}/confirm
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiSE9TVCIsInVzZXJJZCI6IjQiLCJlbWFpbCI6InZlcmdhcmF3aWxsaW50b24wNEBnbWFpbC5jb20iLCJzdWIiOiJ2ZXJnYXJhd2lsbGludG9uMDRAZ21haWwuY29tIiwiaWF0IjoxNzYwMTUwMzQzLCJleHAiOjE3NjAxNTM5NDN9.mAkkBKJHhQ7BCAqC0RJ8X5nMauKlPu3GqbQO136CRks2bDW__RZpcWGJskhg1c5t6dhGMy9ekVeiGZ6EK9yLwA

###Bookin's cancelation
PUT http://localhost:8080/bookings/{{bookingId}}/cancel
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiSE9TVCIsInVzZXJJZCI6IjQiLCJlbWFpbCI6InZlcmdhcmF3aWxsaW50b24wNEBnbWFpbC5jb20iLCJzdWIiOiJ2ZXJnYXJhd2lsbGludG9uMDRAZ21haWwuY29tIiwiaWF0IjoxNzYwMTUwMzQzLCJleHAiOjE3NjAxNTM5NDN9.mAkkBKJHhQ7BCAqC0RJ8X5nMauKlPu3GqbQO136CRks2bDW__RZpcWGJskhg1c5t6dhGMy9ekVeiGZ6EK9yLwA