### Booking HTTP tests for BookingServiceImpl via BookingController

@bookingId = 4

###Create booking
POST http://localhost:8080/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiSE9TVCIsInVzZXJJZCI6IjQiLCJlbWFpbCI6InZlcmdhcmF3aWxsaW50b24wNEBnbWFpbC5jb20iLCJzdWIiOiJ2ZXJnYXJhd2lsbGludG9uMDRAZ21haWwuY29tIiwiaWF0IjoxNzYwMTQwNTQyLCJleHAiOjE3NjAxNDQxNDJ9.gKQohT7_F32Oh34HaoLGrcX0O4RRmfNMTXuDZ5TUSRO3ivsvwRmdwV883ILDUsPlTzr992qAktsCsTHRKxHrFA

{
  "idUser": 4,
  "idAccommodation": 6,
  "dateCheckIn": "2025-10-13",
  "dateCheckOut": "2025-10-15",
  "guestsCount": 4,
  "status": "PENDING",
  "price": 230000.0,
  "notes": "OMG necesito una piscina para bañarme"
}

###Bookin's cancelation
PUT http://localhost:8080/bookings/{{bookingId}}/cancel