### Comment HTTP tests for CommentServiceImpl via CommentController

### Create Comment
POST http://localhost:8080/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiR1VFU1QiLCJ1c2VySWQiOiIxIiwiZW1haWwiOiJyb2pvQGdtYWlsLmNvbSIsInN1YiI6InJvam9AZ21haWwuY29tIiwiaWF0IjoxNzYwMjAxMjU4LCJleHAiOjE3NjAyMDQ4NTh9.5LVp_U3tSXdw_cg5aGNK0_-oPNdDFtI1zQcN87goflaFOZWesMNZiiexwDs0eIIvpexxN0X4rZCtm929EoJ08g

{
  "rating" : 1,
  "comment" : "No me gustó la experiencia, muy mala hijuemadre",
  "idBooking": 11
}

### Answer comment
POST http://localhost:8080/comments/answer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiSE9TVCIsInVzZXJJZCI6IjQiLCJlbWFpbCI6InZlcmdhcmF3aWxsaW50b24wNEBnbWFpbC5jb20iLCJzdWIiOiJ2ZXJnYXJhd2lsbGludG9uMDRAZ21haWwuY29tIiwiaWF0IjoxNzYwMTk5OTcyLCJleHAiOjE3NjAyMDM1NzJ9.q-QLqDY-O4j0v54rUbDO4ER5l6nBzOEShqw-CvXfkBAqL8lh7NazMZkxZLBX76DQlVFMXVeaUFpbh1ah8uPWaw

{
  "answer": "Me alegra que les haya gustado la estadía",
  "idComment": 1
}