### Metric HTTP tests for MetricServiceImpl via MetricController
@id = 19

### Accommodation's metric
POST http://localhost:8080/metrics/accommodations/{{id}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiSE9TVCIsInVzZXJJZCI6IjEiLCJlbWFpbCI6InZlcmdhcmF3aWxsaW50b24wNEBnbWFpbC5jb20iLCJzdWIiOiIxIiwiaWF0IjoxNzYzMTU2NzI2LCJleHAiOjE3NjMxNjAzMjZ9.jS4hZOILYlJ9DMSUkqE4r6bPCg0PX6-BytO9buaeFOOE6WYcI-HOkEes3HP5Qh181sKTwbWDcKiX0tkKNKOGfA

{
  "firstDate": "2025-09-30",
  "lasDate": "2025-12-01"
}

### Host's metric
GET http://localhost:8080/metrics/metrics/summary
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiSE9TVCIsInVzZXJJZCI6IjIiLCJlbWFpbCI6InBhYmxvLmxvcGV6LmcyMDA1QGdtYWlsLmNvbSIsInN1YiI6InBhYmxvLmxvcGV6LmcyMDA1QGdtYWlsLmNvbSIsImlhdCI6MTc2MDI0NDUwNiwiZXhwIjoxNzYwMjQ4MTA2fQ.aqzS4nOuCJ_kc3XX90mYp5pPg_Ta3EfziSdNbXlTg3DbvDipEUI2JUG2a4TDSJnicqKmus3xm2S3UAeOpPJ2bg

{
  "firstDate": "2025-09-30",
  "lasDate": "2025-11-01"
}