### Metric HTTP tests for MetricServiceImpl via MetricController
@id = 6

### Accommodation's metric
GET http://localhost:8080/metrics/accommodations/{{id}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiSE9TVCIsInVzZXJJZCI6IjQiLCJlbWFpbCI6InZlcmdhcmF3aWxsaW50b24wNEBnbWFpbC5jb20iLCJzdWIiOiJ2ZXJnYXJhd2lsbGludG9uMDRAZ21haWwuY29tIiwiaWF0IjoxNzYwMjIxMTI2LCJleHAiOjE3NjAyMjQ3MjZ9.xgux3NGklEXDkZKBAUPUUeBbqN9YybUzPUwRWel2AeI7GDKw1G-Xc6WhipiX2MNRdpplZwvxOdRoFAPcccOiSA

{
  "firstDate": "2025-09-30",
  "lasDate": "2025-11-01"
}

### Host's metric
GET http://localhost:8080/metrics/metrics/summary
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiSE9TVCIsInVzZXJJZCI6IjQiLCJlbWFpbCI6InZlcmdhcmF3aWxsaW50b24wNEBnbWFpbC5jb20iLCJzdWIiOiJ2ZXJnYXJhd2lsbGludG9uMDRAZ21haWwuY29tIiwiaWF0IjoxNzYwMjIxMTI2LCJleHAiOjE3NjAyMjQ3MjZ9.xgux3NGklEXDkZKBAUPUUeBbqN9YybUzPUwRWel2AeI7GDKw1G-Xc6WhipiX2MNRdpplZwvxOdRoFAPcccOiSA

{
  "firstDate": "2025-09-30",
  "lasDate": "2025-11-01"
}